#!/bin/sh -e

if test -z "$1"
then
    echo "usage: $0 ~/rpmbuild/SOURCES/mercury-srcdist-*.tar.gz"
    exit 1
fi

tarball=$1
if test ! -f "$tarball"
then
    echo "Expected source tarball: $tarball" 1>&2
    exit 1
fi

base=$( basename $tarball )
base=${base%.tar.*}
version=${base#mercury-srcdist-}
case $version in
    rotd-2[0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9])
        ;;
    [0-9][0-9]*-beta-*)
        ;;
    [0-9][0-9].[0-9][0-9]*)
        ;;
    *)
        echo "Could not extract version from filename: $tarball" 1>&2
        exit 1
        ;;
esac

echo "Version $version"

version_with_underscores=${version//-/_}

echo "Building binary package:"
rpmbuild -bb mercury-compiler.spec \
   -D"VERSION $version" \
   -D"VERSION_WITH_UNDERSCORES ${version_with_underscores}"

echo "done."
exit 0

# vim: set et:
